version: "3.8"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:19
    depends_on:
      - postgresql
    ports:
      - "80:8080"
      
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
  
  api:
    build: ./api
    ports:
      - 8081:5000
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: flask run --host 0.0.0.0 --port 5000
    depends_on:
      - db
      - keycloak

  web:
    build: ./web
    ports:
      - 8080:5000
    command: flask run --host 0.0.0.0 --port 5000
    volumes:
      - ./web:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - api

volumes:
  postgresql_data:
    driver: local