version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - 1338:8080
    environment:
      # - KC_DB_URL=jdbc:h2://db-auth:1337/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=admin
      # - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/admin
    depends_on:
      - db-auth
    entrypoint: /opt/keycloak/bin/kc.sh
    command: start

  db-auth:
    image: postgres:13-alpine
    restart: always
    ports:
      - 1337:5432
    volumes:
      - ./auth/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      
  # db:
  #   image: postgres:13-alpine
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: admin
  
  # web:
  #   build: ./web
  #   ports:
  #     - 8080:5000
  #   command: flask run --host=0.0.0.0 --port=5000
  #   volumes:
  #     - ./web:/usr/src/app
  #   working_dir: /usr/src/app
  #   depends_on:
  #     - db